# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: locale/|^tabbycat/static/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude_types:
    - csv
    - svg
  - id: check-yaml
  - id: check-added-large-files
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-import-order
    - flake8-quotes
    - pep8-naming
    - flake8-commas
    exclude: migrations/
