# Generated by Django 2.2.4 on 2019-12-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0013_rename_test_score'),
        ('tournaments', '0006_auto_20191109_1240'),
        ('venues', '0006_auto_20191217_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('start_time', models.TimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Juge',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participants.Person')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament')),
            ],
            bases=('participants.person',),
        ),
        migrations.CreateModel(
            name='Orateur',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participants.Person')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament')),
            ],
            bases=('participants.person',),
        ),
        migrations.CreateModel(
            name='OrateurSalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(blank=True, help_text='0 points en dernier place', null=True)),
                ('orateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discours.Orateur')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discours.Joute')),
                ('juges', models.ManyToManyField(to='discours.Juge')),
                ('orateurs', models.ManyToManyField(through='discours.OrateurSalle', to='discours.Orateur')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.Venue')),
            ],
        ),
        migrations.AddField(
            model_name='orateursalle',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discours.Salle'),
        ),
    ]
