# Generated by Django 2.2.4 on 2019-12-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20191109_1240'),
        ('discours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juge',
            name='tournament',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orateur',
            name='tournament',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orateursalle',
            name='points',
            field=models.PositiveIntegerField(blank=True, help_text='0 points en dernier place', null=True),
        ),
    ]
