# Generated by Django 2.2.9 on 2020-01-10 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('discours', '0002_auto_20200110_0112'), ('discours', '0003_auto_20200110_0113')]

    dependencies = [
        ('discours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juge',
            old_name='person_ptr',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='juge',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='participants.Person'),
        ),
        migrations.RenameField(
            model_name='orateur',
            old_name='person_ptr',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='orateur',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='participants.Person'),
        ),
        migrations.AlterField(
            model_name='orateursalle',
            name='orateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discours.Orateur'),
        ),
    ]
