# Generated by Django 2.2.4 on 2019-11-22 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0006_auto_20191109_1240'),
        ('participants', '0013_auto_20191109_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=40, unique=True, verbose_name='reference')),
                ('checkout', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('order', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('methode', models.CharField(choices=[('o', 'En ligne'), ('c', 'Par crédit'), ('p', 'En comptant'), ('v', 'Void')], max_length=1)),
                ('statut', models.CharField(choices=[('f', 'Payé'), ('o', 'Ouvert'), ('a', 'Annulé')], max_length=1)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.Institution', verbose_name='école')),
                ('personnes', models.ManyToManyField(to='participants.Person', verbose_name='personnes')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.Tournament', verbose_name='tournament')),
            ],
        ),
    ]
